/**
 * Core types for Remote Task system
 * 
 * Design Principles:
 * - Authentication design inspired by industry best practices (OAuth2, request interceptors)
 * - Unified tool structure
 * - Supports both sync and async tool types
 */

// ============================================================================
// Connector Types
// ============================================================================

export interface Connector {
    id?: string;
    name?: string;
    description?: string;
    icon?: string;
    version?: string;

    // Authentication configuration
    authentication: Authentication;

    // HTTP interceptors
    beforeRequest?: RequestInterceptor[];
    afterResponse?: ResponseInterceptor[];

    // Tool definitions (unified structure)
    tools: Record<string, Tool>;
}

// ============================================================================
// Tool Types
// ============================================================================

export interface Tool {
    key: string;
    name: string;
    description: string;
    kind: 'sync' | 'async';

    // Input/output definitions
    inputFields: InputField[];
    outputFields?: OutputField[];
    sample?: any;

    // Execution function
    perform: PerformFunction;

    // Async tool specific
    webhookHandler?: WebhookHandlerFunction;  // Handle external platform callbacks
    checkStatus?: CheckStatusFunction;        // Proactively check status
    cancelRequest?: CancelRequestFunction;     // Cancel a running task
}

// ============================================================================
// Perform Function Types
// ============================================================================

export type PerformFunction = (
    z: RuntimeContext,
    bundle: Bundle
) => Promise<SyncResult | AsyncResult>;

export type WebhookHandlerFunction = (
    z: RuntimeContext,
    bundle: WebhookBundle
) => Promise<WebhookResult>;

export type CheckStatusFunction = (
    z: RuntimeContext,
    bundle: CheckBundle
) => Promise<CheckResult>;

export type CancelRequestFunction = (
    z: RuntimeContext,
    bundle: CancelBundle
) => Promise<CancelResult>;

// ============================================================================
// Result Types
// ============================================================================

// Sync tool return
export interface SyncResult {
    [key: string]: any;
}

// Async tool return
export interface AsyncResult {
    taskId: string;           // External platform task ID
    status: TaskStatus;

    // Task detail page (for App WebView to open)
    taskInfoUrl?: string;

    // Callback mechanism
    webhookSupported: boolean;
}

// Webhook handler return
export interface WebhookResult {
    status: TaskStatus;
    result?: any;
    error?: any;
}

// Status check return
export interface CheckResult {
    status: TaskStatus;
    result?: any;
    error?: any;
}

// Cancel request return
export interface CancelResult {
    status: 'cancelled' | 'pending';  // cancelled: immediately cancelled, pending: cancellation in progress
    message?: string;
}

export type TaskStatus = 'pending' | 'running' | 'completed' | 'failed' | 'cancelled' | 'action_required';

// ============================================================================
// Bundle Types
// ============================================================================

export interface Bundle {
    authData: AuthData;
    inputData: Record<string, any>;
    vars?: Record<string, any>;      // Environment variables (non-sensitive)
    secrets?: Record<string, any>;   // Secrets (sensitive, encrypted)
    meta?: BundleMeta;
}

export interface WebhookBundle extends Bundle {
    rawRequest: {
        method: string;
        headers: Record<string, string>;
        body: any;
    };
    cleanedRequest: Record<string, any>;
}

export interface CheckBundle extends Bundle {
    inputData: {
        taskId: string;
        [key: string]: any;
    };
}

export interface CancelBundle extends Bundle {
    inputData: {
        taskId: string;  // External platform task ID
        [key: string]: any;
    };
}

export interface AuthData {
    access_token?: string;
    refresh_token?: string;
    expires_at?: number;  // Unix timestamp (ms)
    [key: string]: any;
}

export interface BundleMeta {
    webhookUrl?: string;    // Callback URL generated by Host
    executionId?: string;   // Execution ID
    isLoadingSample?: boolean;
    [key: string]: any;
}

// ============================================================================
// Input/Output Field Types
// ============================================================================

export interface InputField {
    key: string;
    label: string;
    type?: 'string' | 'text' | 'integer' | 'number' | 'boolean' | 'datetime' | 'file' | 'password';
    required?: boolean;
    default?: any;
    helpText?: string;
    placeholder?: string;
    choices?: Array<string | { label: string; value: string }>;
    list?: boolean;
    children?: InputField[];
    dynamic?: string;
}

export interface OutputField {
    key: string;
    label: string;
    type?: string;
}

// ============================================================================
// Authentication Types
// ============================================================================

export type Authentication =
    | OAuth2Authentication
    | APIKeyAuthentication
    | SessionAuthentication
    | BasicAuthentication
    | CustomAuthentication;

// OAuth2 authentication
export interface OAuth2Authentication {
    type: 'oauth2';
    oauth2Config: {
        authorizeUrl: AuthorizeUrlConfig | AuthorizeUrlFunction;
        getAccessToken: GetAccessTokenFunction;
        refreshAccessToken?: RefreshAccessTokenFunction;
        autoRefresh?: boolean;
        scope?: string;
    };
    fields?: InputField[];
    test: TestFunction;
    connectionLabel?: string | ConnectionLabelFunction;
}

export interface AuthorizeUrlConfig {
    url: string;
    params: Record<string, string>;
}

export type AuthorizeUrlFunction = (
    z: RuntimeContext,
    bundle: AuthBundle
) => Promise<string>;

// API Key authentication
export interface APIKeyAuthentication {
    type: 'api_key';
    fields: InputField[];
    test: TestFunction;
    connectionLabel?: string | ConnectionLabelFunction;
}

// Session authentication
export interface SessionAuthentication {
    type: 'session';
    fields: InputField[];
    test: TestFunction;
    connectionLabel?: string | ConnectionLabelFunction;
}

// Basic authentication
export interface BasicAuthentication {
    type: 'basic';
    fields?: InputField[]; // Username/Password are implicit if missing
    test: TestFunction;
    connectionLabel?: string | ConnectionLabelFunction;
}

// Custom authentication
export interface CustomAuthentication {
    type: 'custom';
    fields: InputField[];
    test: TestFunction;
    connectionLabel?: string | ConnectionLabelFunction;
}

// Authentication function types
export type GetAccessTokenFunction = (
    z: RuntimeContext,
    bundle: AuthBundle
) => Promise<TokenResult>;

export type RefreshAccessTokenFunction = (
    z: RuntimeContext,
    bundle: AuthBundle
) => Promise<Partial<TokenResult>>;

export type TestFunction = (
    z: RuntimeContext,
    bundle: Bundle
) => Promise<any>;

export type ConnectionLabelFunction = (
    z: RuntimeContext,
    bundle: Bundle
) => Promise<string>;

export interface AuthBundle extends Bundle {
    inputData: {
        code?: string;
        state?: string;
        redirect_uri?: string;
        [key: string]: any;
    };
}

export interface TokenResult {
    access_token: string;
    refresh_token?: string;
    expires_in?: number;
    token_type?: string;
    scope?: string;
    [key: string]: any;
}

// ============================================================================
// RuntimeContext Types
// ============================================================================

export interface RuntimeContext {
    request: (options: RequestOptions) => Promise<HttpResponse>;

    console: {
        log: (...args: any[]) => void;
        error: (...args: any[]) => void;
    };

    errors: {
        Error: new (message: string) => Error;
        HaltedError: new (message: string) => Error;
        ExpiredAuthError: new (message?: string) => Error;
        RefreshAuthError: new (message?: string) => Error;
    };

    JSON: {
        parse: (text: string) => any;
        stringify: (value: any) => string;
    };

    template: (template: string, context: Record<string, any>) => string;
}

// ============================================================================
// HTTP Types
// ============================================================================

export interface RequestOptions {
    url: string;
    method?: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS';
    headers?: Record<string, string>;
    params?: Record<string, any>;
    body?: any;
    form?: Record<string, any>;
    json?: any;
    skipThrowForStatus?: boolean;
}

export interface HttpResponse<T = any> {
    status: number;
    headers: Record<string, string>;
    content: string;
    data: T;
    request: RequestOptions;

    throwForStatus: () => void;
    getHeader: (name: string) => string | undefined;
}

// ============================================================================
// Interceptor Types
// ============================================================================

export type RequestInterceptor = (
    request: RequestOptions,
    z: RuntimeContext,
    bundle: Bundle
) => RequestOptions | Promise<RequestOptions>;

export type ResponseInterceptor = (
    response: HttpResponse,
    z: RuntimeContext,
    bundle: Bundle
) => HttpResponse | Promise<HttpResponse>;
