/* eslint-disable */
/* tslint:disable */
/**
 * ---------------------------------------------------------------
 * ## THIS FILE WAS AUTO-GENERATED BY generate-api-wrapper.js  ##
 * ## DO NOT EDIT MANUALLY                                      ##
 * ---------------------------------------------------------------
 *
 * This wrapper automatically unwraps Pin framework response format:
 * - Success: { data: T, trace_id: string } -> T
 * - Error: { error: string, ... } -> throws ApiError
 */
import { Api as GeneratedApi } from './api';
/**
 * Custom API Error class
 */
export class ApiError extends Error {
    key;
    meta;
    status;
    traceId;
    statusCode;
    constructor(message, key, meta, status, traceId, statusCode) {
        super(message);
        this.key = key;
        this.meta = meta;
        this.status = status;
        this.traceId = traceId;
        this.statusCode = statusCode;
        this.name = 'ApiError';
    }
}
/**
 * Unwrap Pin response data field
 */
function unwrapData(promise) {
    return promise
        .then(response => {
        // Check if response has error field (error response)
        const errorResponse = response;
        if (errorResponse.error) {
            throw new ApiError(errorResponse.error, errorResponse.key, errorResponse.meta, errorResponse.status, errorResponse.trace_id);
        }
        // Return unwrapped data
        return response.data;
    })
        .catch(error => {
        // Handle HTTP errors
        if (error instanceof ApiError) {
            throw error;
        }
        // Handle network errors or other exceptions
        if (error.response) {
            const errorData = error.response.data;
            throw new ApiError(errorData?.error || error.message || 'Unknown error', errorData?.key, errorData?.meta, errorData?.status, errorData?.trace_id, error.response.status);
        }
        throw new ApiError(error.message || 'Network error');
    });
}
/**
 * Create wrapped API instance
 */
export function createApi(config) {
    const rawApi = new GeneratedApi(config);
    const wrappedApi = {};
    // Wrap each namespace
    wrappedApi.developer = {};
    for (const key in rawApi.developer) {
        const method = rawApi.developer[key];
        if (typeof method === 'function') {
            wrappedApi.developer[key] = (...args) => unwrapData(method.apply(rawApi.developer, args));
        }
    }
    return wrappedApi;
}
// Re-export all types from generated API
export * from './api';
