echo "====================================="
echo "Example Connector测试指南"
echo "====================================="
echo ""
echo "由于Mock Service Provider尚未部署，无法进行完整的集成测试。"
echo "但我们可以验证connector的代码结构和类型定义。"
echo ""
echo "测试步骤:"
echo ""
echo "1. 部署Mock Service Provider:"
echo "   cd /Users/wanglei/Projects/notelogic/edge/cloudflare/mock-service-provider"
echo "   npm install"
echo "   npm run deploy"
echo ""
echo "2. 配置认证 (获取base_url和api_key):"
echo "   cd /Users/wanglei/Projects/notelogic/remotetask/connectors/connector-example"
echo "   # 编辑 .env 文件或使用交互配置"
echo ""
echo "3. 测试同步工具:"
echo "   npx linktool test run sync_transform -P type=transform -P input='{\"text\":\"hello\"}'"
echo ""
echo "4. 测试异步工具 (需要webhook支持):"
echo "   npx linktool test run async_process --async -P type=process -P input='{\"data\":\"test\"}'"
echo ""
echo "====================================="
echo "Connector 代码结构验证"
echo "====================================="
echo ""
echo "✓ Authentication: API Key 认证"
echo "✓ BeforeRequest: URL和认证header处理"
echo "✓ Sync Tool: sync_transform"
echo "✓ Async Tool: async_process (perform + webhookHandler + checkStatus)"
echo ""
echo "所有代码文件已创建完成，等待部署和测试。"
